### ISSUE TITLE
Error: Invalid expanding argument value

### ISSUE THREAD

**Issue by BartoszZawadzki** [cloudposse/terraform-datadog-platform#22]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
I've been trying to use terraform-datadog-monitor to create some k8s monitors using the provided example. 
Whenever I try to do terraform plan I get:

```hcl
Error: Invalid expanding argument value

  on .terraform/modules/yaml_config/main.tf line 32, in locals:
  31:
  32:     flatten(
  33:       [
  34:         for c in local.local_map_config_paths : [
  35:           for f in fileset(var.map_config_local_base_path, c) : {
  36:             for k, v in yamldecode(templatefile(format("%s/%s", var.map_config_local_base_path, f), var.parameters)) : k => v
  37:           }
  38:         ]
  39:       ]
  40:     )
  41:

The expanding argument (indicated by ...) must be of a tuple, list, or set
type.


Error: Invalid expanding argument value

  on .terraform/modules/yaml_config/main.tf line 45, in locals:
  44:
  45:     [
  46:       for c in local.remote_map_config_paths : {
  47:         for k, v in yamldecode(data.template_file.this[base64encode(c)].rendered) : k => v
  48:       }
  49:     ]
  50:

The expanding argument (indicated by ...) must be of a tuple, list, or set
type.

ERROR: Terraform plan failed
```

## Expected Behavior
Plan doesn't fail and outputs resource changes.

## Steps to Reproduce
1. Copy the example from: https://github.com/cloudposse/terraform-datadog-monitor/tree/master/examples/complete
2. Copy some monitors from: https://github.com/cloudposse/terraform-datadog-monitor/blob/master/catalog/k8s.yaml
3. Perform terraform plan

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: OSX
 - Version 10.15.7

## Additional Context
I'm using terraform-scaffold to manage terraform code: https://github.com/tfutils/tfscaffold

**Comment by Gowiem** [comment]
@BartoszZawadzki I've seen this error in our tests and I believe it's due to using v0.12. You need to be using Terraform v0.13 to use this module. We'll update the provider version to reflect that.

Thanks for the issue, please let me know if using v0.13 fixes the issue for you.

**Comment by nitrocode** [comment]
@BartoszZawadzki now that [versions.tf has been bumped to terraform 0.13](https://github.com/cloudposse/terraform-datadog-platform/blob/2903e8fed20953815f2f1679da73462e4e771a27/versions.tf#L2), could you try the above again and see if using a more recent terraform version solves this issue ?
