### ISSUE TITLE
Unable to add multiple URl's in yaml file

### ISSUE THREAD

**Issue by MohitDubeyGitHub** [cloudposse/terraform-datadog-platform#37]
While writing the yaml file it doesn't take any other title apart from Simple and complex . How we can add multiple test in a single yaml file

**Comment by Benbentwo** [comment]
Hoping to get a little bit more information. is this for Monitors, Synthetics, or SLOs? 

In a given yaml file - that is targed by a `<type>_config_path` variable, such as `datadog_monitors_config_paths` - we can specify multiple monitors, synthetics or slos by separating by root key.

Our Catalog has some examples of this - [in monitors](https://github.com/cloudposse/terraform-datadog-platform/blob/master/catalog/monitors/k8s.yaml) for example

**Comment by Nuru** [comment]
I am closing this due to lack of information from the OP. It can be reopened if further details are provided.
