### ISSUE TITLE
Support setting tags as a single string

### ISSUE THREAD

**Issue by jmctune** [cloudposse/terraform-datadog-platform#90]
### Describe the Feature

Datadog supports adding non key:value pairs of tags on a monitor. This module appears to force a key:value pair if the key does not exist.

For example, I have defined:

```hcl
tags = ["AWS", "Terraform", "EKS"]
```

What this does is add the following tags to the datadog monitors:

- `0:AWS`
- `1:Terraform`
- `2:EKS`

### Expected Behavior

I would like to be able to add a list of tags without prepending their list position as a key for each of the tags.

These tags should instead be added to the monitor:

- `AWS`
- `Terraform`
- `EKS`

### Use Case

Datadog supports adding tags this way, so I'd like to add tags as such.

### Describe Ideal Solution

N/A

**Comment by jmctune** [comment]
Ok, this may be working as intended and an issue with how we're calling this module. I am working with some existing code and noticed that we're pinning directly to the `monitors` module.

Apologies for the noise; I will close this.

**Comment by jnewton-tw** [comment]
> Ok, this may be working as intended and an issue with how we're calling this module. I am working with some existing code and noticed that we're pinning directly to the `monitors` module.
> 
> Apologies for the noise; I will close this.

How did you fix this? Thanks!
